"""m2m readers_books

Revision ID: dc0f8428b706
Revises: 2ac835118cf8
Create Date: 2022-12-19 21:13:00.169588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc0f8428b706'
down_revision = '2ac835118cf8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
